_target_: datasets.cars_module.CarsModule
train:
  batch_size: 96
  shuffle: True
  num_workers: 4
  drop_last: False
  pin_memory: True
  collate_fn: null
val:
  batch_size: ${data_module.train.batch_size}
  shuffle: False
  num_workers: ${data_module.train.num_workers}
  drop_last: False
  pin_memory: True
  collate_fn: null
test: ${data_module.val}