seed: 69
log: True
cpu: 1
gpu: 1
num_nodes: 1

defaults:
  - _self_
  - model: diffusion
  - data_module: max
  - dataset: cars
  - transform: car_transform
  - loss: mse
  - user_overrides: null

callbacks:

tasks:
  _target_: tasks.generate_car_img.DiffusionModule
  

pretrained: tb_logs\lightning_logs\version_2\checkpoints\epoch=34-step=5915.ckpt # add path to the pretrained weights