train:
  _target_: dataset.cars.Cars
  data_dir: ${hydra:runtime.cwd}/data
  transform: null
val:
  _target_: dataset.cars.CarsTest
  data_dir: ${hydra:runtime.cwd}/data
  transform: null
test: 
  _target_: dataset.cars.CarsTest
  data_dir: ${hydra:runtime.cwd}/data
  transform: null