train:
  _target_: dataset.e2e_nlg.NLGDataset
  split: "train"
  tokenizer: null
val:
  _target_: dataset.e2e_nlg.NLGDataset
  split: "validation"
  tokenizer: null
test: 
  _target_: dataset.e2e_nlg.NLGDataset
  split: "test"
  tokenizer: null